/**
 * The Rally mark, as geometry.
 *
 * GENERATED by scripts/make-icons.mjs — run `npm run icons` after changing
 * SPEC there. Editing this file by hand puts the launch screen and the app icon
 * out of step, which is the one thing having a generator was meant to prevent.
 *
 * The R is Bricolage Grotesque ExtraBold converted to outlines, so nothing here
 * depends on a font being loaded — which matters, because the launch screen is
 * on screen precisely while the fonts are still loading.
 */

/** Both the viewBox width and height. The mark is drawn on a square. */
export const MARK_CANVAS = 1024;

/** One R, as a path. Draw it three times at the offsets below. */
export const MARK_PATH = 'M128.465 0L38.540 0L38.540-368.640L195.491-368.640Q226.211-368.640 251.345-363.892Q276.480-359.145 295.750-349.929Q315.020-340.713 328.425-327.587Q341.830-314.461 348.532-297.425Q355.235-280.390 355.235-259.724Q355.235-240.175 349.091-224.535Q342.947-208.896 330.380-197.167Q317.812-185.437 298.822-178.176Q279.831-170.915 254.697-167.564L254.697-159.185Q286.534-155.834 304.128-144.943Q321.722-134.051 331.217-116.177Q340.713-98.304 347.974-73.169L369.199 0L269.219 0L253.021-67.584Q247.994-89.926 239.337-102.214Q230.679-114.502 217.274-119.249Q203.869-123.997 183.761-123.997L128.465-123.997L128.465 0M128.465-300.497L128.465-190.464L189.347-190.464Q223.418-190.464 242.409-203.869Q261.399-217.274 261.399-245.760Q261.399-273.687 244.084-287.092Q226.769-300.497 191.581-300.497';

/** Bottom letter first, so a stagger animates as a climb. */
export const MARK_LETTERS: { x: number; y: number }[] = [{"x":57.46,"y":954.37},{"x":308.13,"y":696.32},{"x":558.81,"y":438.27}];

/** The channel that keeps overlapping letters apart, in canvas units. */
export const MARK_GAP = 20;
