/**
 * The Rally mark, as geometry.
 *
 * GENERATED by scripts/make-icons.mjs — run `npm run icons` after changing
 * SPEC there. Editing this file by hand puts the launch screen and the app icon
 * out of step, which is the one thing having a generator was meant to prevent.
 *
 * Five wedges on a 72° rotation closing on one core. Pure geometry: nothing
 * here depends on a font being loaded, which matters, because the launch screen
 * is on screen precisely while the fonts are still loading.
 */

/** Both the viewBox width and height. The mark is drawn on a square. */
export const MARK_CANVAS = 100;

/** Everything rotates about this point, on both axes. */
export const MARK_CENTER = 50;

/** One wedge. Draw it once per angle below. */
export const MARK_WEDGE = 'M38 6 L62 6 L57 44 Z';

/** The thickened cut, for sizes where the standard one turns to lace. */
export const MARK_WEDGE_SMALL = 'M36 4 L64 4 L58 44 Z';

/** Five of them, 72° apart. The spacing is the mark. */
export const MARK_ANGLES: number[] = [0,72,144,216,288];

/** Core radius, two-tone — the one element that changes between colorways. */
export const MARK_CORE_R = 13;

/** Core radius for the one-colour cut, grown so the huddle fuses. */
export const MARK_CORE_R_SOLID = 15;

/** Core radius for the small cut, paired with `MARK_WEDGE_SMALL`. */
export const MARK_CORE_R_SMALL = 17;

/**
 * Optical centring nudge, canvas units. The mark is five-fold symmetric about
 * the centre but its ink box is not — 5-fold has no mirror across the
 * horizontal — so drawn on the raw frame it sits this far high.
 */
export const MARK_NUDGE_Y = 0.675;
